# config.yaml
# Parametri di esempio per ambiente e credenziali
azure:
  client_id: "YOUR_CLIENT_ID"
  client_secret: "YOUR_CLIENT_SECRET"
  tenant_id: "YOUR_TENANT_ID"

workspaces:
  - "workspace_id_1"
  - "workspace_id_2"

database:
  path: "./data/semantic_metadata.db"
